### ISSUE TITLE
which version of deepspeed?

### ISSUE THREAD

**Issue by kimpty** [Wangyixinxin/MMedAgent#4]
i use numpy==1.26.3,deepspeed==0.9.5. Version seems to conflict when i run 'sh tuning.sh'?

(mmedagent2) [user01@GPU04 MMedAgent]$ sh tuning.sh 
[2024-11-11 16:57:45,093] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
Traceback (most recent call last):
  File "/home/user01/miniforge3/envs/mmedagent2/bin/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 792, in <module>
    from ..pipe import PipelineModule
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 57, in <module>
    from ..autotuning.config import DeepSpeedAutotuningConfig
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/autotuning/__init__.py", line 6, in <module>
    from .autotuner import Autotuner
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/autotuning/autotuner.py", line 20, in <module>
    from .scheduler import ResourceManager
  File "/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/deepspeed/autotuning/scheduler.py", line 8, in <module>
    from numpy import BUFSIZE
ImportError: cannot import name 'BUFSIZE' from 'numpy' (/home/user01/miniforge3/envs/mmedagent2/lib/python3.10/site-packages/numpy/__init__.py)

**Comment by AndyCA111** [comment]
Hi, this may be related to the version of numpy you're using not deepspeed b/c there is an error when importing package from numpy. Could you double check the numpy version in your current environment? You can display your pip list. If you have installed the required version 1.26.3 but are still experiencing this issue, please don’t hesitate to ask again, and I'll help you resolve it.

**Comment by kimpty** [comment]
yes,it is related to the version of numpy. thank you
